import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from "next/head";
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import React from "react";

function MyApp({ Component, pageProps }: AppProps) {
  return (<>

    <Head>
      <script
          type="text/javascript"
          src={"https://maps.googleapis.com/maps/api/js?key=AIzaSyAyi_dL2s3UqyOc1-vrtQP-mHlGYbNS0u4&libraries=places"}
      />
      <title>commutio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  <body
      className="main"
  >

  <Component {...pageProps} />
  </body>
    </>)
}

export default MyApp